name: 问题反馈 / Bug report
title: '[BUG] '
description: 反馈你遇到的问题 / Report the issue you are experiencing
body:
  - type: markdown
    attributes:
      value: |
        感谢您花时间填写, 在提交问题之前, 请确保您完成以下操作
  - type: checkboxes
    id: checkboxes
    attributes:
      label: 一些验证
      description: 在提交问题之前，请确保您完成以下操作
      options:
        - label: 请 **确保** 您已经检查这个问题是否属于 [本项目维护的规则](https://github.com/MengNianxiaoyao/gkd-subscription) 导致
          required: true
        - label: 请 **确保** 您的问题能在 [GKD releases](https://github.com/gkd-kit/gkd/releases/latest) 发布的最新版本(包含测试版本)上复现 (如果不是请先更新到最新版本复现后再提交问题)
          required: true
        - label: 请 **确保** 您已经搜索检查是否已经存在请求相同功能的问题/讨论，否则请在已有的issue下进行讨论，以避免重复创建问题
          required: true
        - label: 请 **确保** 知晓并同意维护者直接关闭不符合 issue 规范的问题
          required: true
        - label: 请 **确保** 提供下列BUG描述及其复现步骤, 否则您的问题将会被直接关闭
          required: true
  - type: textarea
    id: bug-1
    attributes:
      label: |
        BUG描述(文字/截图/视频)
      description: |
        请输入 BUG 描述及其复现步骤，请使用尽量准确的描述, 否则你的问题将会被直接关闭。
    validations:
      required: true
  - type: textarea
    id: feature-description
    attributes:
      label: |
        请输入 误触/不执行规则 的界面的快照, 或者生成的快照链接
      description: |
        请注意: 不提供快照或者仅提供截图的 issue 将被自动关闭 \
        快照是一个 zip 文件, 快照链接是类似 "https://i.gkd.li/import/XXXXXXXX" 或 "https://i.gkd.li/i/XXXXXXXX" 的文本。\
        如果你不了解什么是快照，请先阅读[ GKD 相关文档](https://gkd.li/guide/snapshot)
    validations:
      required: true
